### PR TITLE
Update package-lock

### PR DESCRIPTION
**Pull request by Charles-Gagnon**
Github was detecting a dependency on an insecure version of tar but this repo doesn't actually have a dependency on that. It just had an outdated package-lock.

### CODE REVIEW

**Comment by anthonydresser** [comment]
We should just delete the lock; we use yarn here anyways.

**Comment by anthonydresser** [comment]
Can you update the PR to delete the package-lock

**Comment by anthonydresser** [comment]
We want to keep the npmignore. Yarn respects that when you create a release build.

**Comment by Charles-Gagnon** [comment]
Ah, thanks. Is that documented anywhere? I looked around and didn't seem to find anything referencing that so figured it was safe to remove.

**Comment by anthonydresser** [comment]
I'm actually not sure its documented anywhere. Yarn was designed to just work natively with npm with the exception of its own lock file.

**Review by anthonydresser — APPROVED** [review]

**Pull request merged**
